configured_endpoints: 2
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/test-arockiyaagithub%2Faro-test-sdk-baadcf5eb03afc387136d046b1de14b2594974bf9dd909d7e27116a5bff34d2e.yml
